#!/usr/bin/env bash
#
# reachy-bridge setup wizard — one-command install for Reachy owners.
#
#   git clone <repo> && cd reachy-bridge && ./scripts/setup.sh
#
# What it does:
#   1. creates a venv and installs requirements
#   2. probes the LAN for a Reachy Mini daemon
#   3. collects your agent's Ed25519 PUBLIC key  (paste it; the private key
#      never leaves your agent's machine — this is the whole point)
#   4. generates a panel token for your browser/phone UI
#   5. writes .env and prints your next steps
#
set -euo pipefail
cd "$(dirname "$0")/.."

say()  { printf '\n\033[1m%s\033[0m\n' "$*"; }
info() { printf '  %s\n' "$*"; }
warn() { printf '  \033[33mWARNING: %s\033[0m\n' "$*"; }

say "1/5 — Python environment"
command -v python3 >/dev/null || { echo "python3 not found — install it first."; exit 1; }
if [ ! -d .venv ]; then python3 -m venv .venv; info "created .venv"; fi
# shellcheck disable=SC1091
source .venv/bin/activate
pip install -q -r requirements.txt
info "dependencies installed"

say "2/5 — Finding your robot"
MINI_URL=""
for cand in "http://reachy-mini.local:8000/api" "http://localhost:8000/api"; do
  if curl -sm 3 "$cand/state/full-state" >/dev/null 2>&1; then
    MINI_URL="$cand"; info "found Reachy Mini daemon at $cand"; break
  fi
done
if [ -z "$MINI_URL" ]; then
  warn "no Reachy Mini daemon found on the usual addresses."
  read -r -p "  Daemon base URL (e.g. http://192.168.1.42:8000/api), empty to skip: " MINI_URL || true
fi

say "3/5 — Agent access (Ed25519 public key)"
info "Your agent holds the PRIVATE key. You only ever paste the PUBLIC key here."
info "Nothing secret crosses the wire in this step."
mkdir -p clients
if ls clients/*.pub >/dev/null 2>&1; then
  info "existing clients: $(ls clients/*.pub | xargs -n1 basename | tr '\n' ' ')"
fi
read -r -p "  Agent name [astro]: " AGENT_NAME || true
AGENT_NAME="${AGENT_NAME:-astro}"
PUB_FILE="clients/${AGENT_NAME}.pub"
if [ -f "$PUB_FILE" ]; then
  info "keeping existing $PUB_FILE"
else
  info "Paste the agent's public key (one line, starts with ssh-ed25519), then Enter."
  info "Leave empty to add it later with: ./scripts/add-client.sh <name>"
  read -r -p "  > " PUBKEY || true
  if [ -n "${PUBKEY:-}" ]; then
    printf '%s\n' "$PUBKEY" > "$PUB_FILE"
    info "saved to $PUB_FILE"
  else
    warn "no key added — signed API calls will 401 until you add one."
  fi
fi

say "4/5 — Panel token (your browser/phone UI)"
if command -v openssl >/dev/null; then
  PANEL_TOKEN="$(openssl rand -hex 16)"
else
  PANEL_TOKEN="$(head -c 16 /dev/urandom | od -An -tx1 | tr -d ' \n')"
fi
info "generated (stored in .env, never in git)"

say "5/5 — Writing .env"
if [ -f .env ]; then cp .env .env.bak; warn "existing .env backed up to .env.bak"; fi
{
  echo "# reachy-bridge config — generated by scripts/setup.sh, do not commit"
  echo "BRIDGE_MINI_URL=${MINI_URL}"
  echo "BRIDGE_PORT=8765"
  echo "BRIDGE_PANEL_TOKEN=${PANEL_TOKEN}"
  echo "BRIDGE_CLIENTS_DIR=clients"
  echo "BRIDGE_AUDIT_LOG=audit.log"
  echo "BRIDGE_AUTH_WINDOW=120"
} > .env
info "wrote .env"

say "Done. Next steps:"
info "  1. source .venv/bin/activate && python bridge.py"
info "  2. open http://127.0.0.1:8765/panel  (token is in .env as BRIDGE_PANEL_TOKEN)"
info "  3. in another terminal:  tailscale funnel 8765"
info "  4. send your agent TWO things: the funnel URL + nothing else."
info "     (it already holds its private key; the public key above is all the bridge needs)"
info ""
info "Test without hardware any time:  BRIDGE_MOCK=1 python bridge.py"
